```{r}
url = "https://esgf-data.dkrz.de/esg-search/search/?offset=0&limit=10000&type=Dataset&replica=false&latest=true&experiment_id=hist-GHG%2Chist-aer%2Chist-nat%2Chistorical&frequency=day&variable_id=huss%2Ctasmax&mip_era=CMIP6&activity_id%21=input4MIPs&facets=mip_era%2Cactivity_id%2Cproduct%2Csource_id%2Cinstitution_id%2Csource_type%2Cnominal_resolution%2Cexperiment_id%2Csub_experiment_id%2Cvariant_label%2Cgrid_label%2Ctable_id%2Cfrequency%2Crealm%2Cvariable_id%2Ccf_standard_name%2Cdata_node&format=application%2Fsolr%2Bjson"
URLdecode(url)
```

```{r}
library(Ipaper)
library(httr)
library(xml2)
library(magrittr)
library(jsonlite)
library(dplyr)
```

# 1. 案例1

## 1.1. 获取文件信息
```{r}
scenarios = scenarios_cmip6[4] %>% paste(collapse = ",")

param <- list(
  # variable_id = "tasmax,huss", 
  variable_id = "pr", 
  table_id = "day", 
  experiment_id = scenarios,
  member_id = "r1i1p1f1"
  # member_id = NULL
)

# param <- list(
#   variable_id = "huss",
#   source_id = "E3SM-2-0",
#   experiment_id = "historical"
# )
t <- system.time({
  docs <- retrieve_esgf_docs(param = param)
})
print(t)
```

```{r}
## 1.2. 文件挑选与清洗
url_type <- c("OPENDAP", "HTTPServer")
# url_type <- c("HTTPServer", "OPENDAP")
info <- tidy_esgp_docs(docs, url_type)

## 1.3. 筛选：最新版本、最快节点
# d_host <- ping_host(info$host %>% unique())
info2 <- merge(info, d_host)
info2 %<>% 
  group_by(file) %>% top_n(-1, version) %>%      # lastest version
  group_by(file, version) %>% top_n(-1, speed_ms) %>% # fast node
  select(-host) %>% data.table()
info2 %>% data.table()

s <- CMIP5Files_info(info2[, file]) %>% CMIP5Files_summary()
# s_tas <- CMIP5Files_info(info2[variable == "tasmax", file]) %>% CMIP5Files_summary()

save(info2, s, file = "info_prcp.rda")
writeLines(info2$url, "urls_pr.txt")
```
